const data = [
  {
    nama_barang: "Kaos Polos Hitam",
    slug: "kaos-polos-hitam",
    kategori: "reuse",
    tipe: "kaos",
    harga: 50000,
    stok: 100,
    deskripsi: "Kaos polos berwarna hitam, nyaman dipakai sehari-hari. Bahan katun 100%.",
    image: "https://example.com/images/kaos-polos-hitam.jpg",
  },
  {
    nama_barang: "Celana Jeans Biru",
    slug: "celana-jeans-biru",
    kategori: "reuse",
    tipe: "celana",
    harga: 150000,
    stok: 50,
    deskripsi: "Celana jeans biru dengan desain klasik. Cocok untuk segala acara.",
    image: "https://example.com/images/celana-jeans-biru.jpg",
  },
  {
    nama_barang: "Jaket Denim",
    slug: "jaket-denim",
    kategori: "reuse",
    tipe: "jaket",
    harga: 200000,
    stok: 30,
    deskripsi: "Jaket denim yang stylish dan hangat. Cocok untuk musim dingin.",
    image: "https://example.com/images/jaket-denim.jpg",
  },
  {
    nama_barang: "Rok Mini Polkadot",
    slug: "rok-mini-polkadot",
    kategori: "reuse",
    tipe: "rok",
    harga: 80000,
    stok: 70,
    deskripsi: "Rok mini dengan motif polkadot yang lucu. Bahan nyaman dan elastis.",
    image: "https://example.com/images/rok-mini-polkadot.jpg",
  },
  {
    nama_barang: "Kemeja Flanel Merah",
    slug: "kemeja-flanel-merah",
    kategori: "reuse",
    tipe: "kemeja",
    harga: 120000,
    stok: 40,
    deskripsi: "Kemeja flanel merah dengan motif kotak-kotak. Bahan lembut dan hangat.",
    image: "https://example.com/images/kemeja-flanel-merah.jpg",
  },
  {
    nama_barang: "Blus Putih Elegan",
    slug: "blus-putih-elegan",
    kategori: "reuse",
    tipe: "blus",
    harga: 95000,
    stok: 60,
    deskripsi: "Blus putih dengan desain elegan. Cocok untuk acara formal dan kasual.",
    image: "https://example.com/images/blus-putih-elegan.jpg",
  },
  {
    nama_barang: "Sweater Rajut Abu",
    slug: "sweater-rajut-abu",
    kategori: "reuse",
    tipe: "sweater",
    harga: 110000,
    stok: 45,
    deskripsi: "Sweater rajut abu-abu yang hangat dan nyaman. Desain sederhana dan stylish.",
    image: "https://example.com/images/sweater-rajut-abu.jpg",
  },
  {
    nama_barang: "Cardigan Panjang",
    slug: "cardigan-panjang",
    kategori: "reuse",
    tipe: "cardigan",
    harga: 130000,
    stok: 35,
    deskripsi: "Cardigan panjang yang modis. Bahan lembut dan nyaman dipakai.",
    image: "https://example.com/images/cardigan-panjang.jpg",
  },
  {
    nama_barang: "Celana Jogger",
    slug: "celana-jogger",
    kategori: "reuse",
    tipe: "celana",
    harga: 90000,
    stok: 80,
    deskripsi: "Celana jogger yang nyaman untuk olahraga dan santai. Bahan katun berkualitas.",
    image: "https://example.com/images/celana-jogger.jpg",
  },
  {
    nama_barang: "Tunik Batik",
    slug: "tunik-batik",
    kategori: "reuse",
    tipe: "tunik",
    harga: 160000,
    stok: 25,
    deskripsi: "Tunik batik dengan motif tradisional. Bahan nyaman dan adem.",
    image: "https://example.com/images/tunik-batik.jpg",
  },
];

export default data;
